name: DongTai check for vul-scan

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.2.5
      
      - name: Set up DongTai
        id: dongtai
        uses: exexute/open-agent-action@main
        with:
          project-name: "SpringVulExample"
      
      - name: Run Test
        run: |
          ls -la ~/
          echo "${{ steps.dongtai.outputs.agent-env }}"
          export JAVA_TOOL_OPTIONS="${{ steps.dongtai.outputs.agent-env }}"
          java -version
