name: DongTai check for vul-scan

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.2.5

      - name: Build with Maven
        run: |
          mvn -B package -Dmaven.test.skip=true
          ls -l
      
      - name: Set up DongTai
        id: dongtai
        uses: exexute/open-agent-action@main
        with:
          project-name: "SpringVulExample"
      
      - name: Run Example
        run: |
          source ~/.bash_profile
          mvn test
          sleep 5
